SAVES = {
    'will': 'wis',
    'fortitude': 'con',
    'reflex': 'dex'
    }

SKILLS = {
    'perception': 'wis',
    'acrobatics': 'dex',
    'arcana': 'int',
    'athletics': 'str',
    'crafting': 'int',
    'deception': 'cha',
    'diplomacy': 'cha',
    'intimidation': 'cha',
    'lore': 'int',
    'medicine': 'wis',
    'nature': 'wis',
    'occultism': 'int',
    'performance': 'cha',
    'religion': 'wis',
    'society': 'int',
    'stealth': 'dex',
    'survival': 'wis',
    'thievery': 'dex'
    }

STATS = {
    'str',
    'dex',
    'con',
    'int',
    'wis',
    'cha'
    }

TIME = {
    'round',
    'minute',
    'hour',
    'day'
    }

CONDITIONS = {
    'friendly',
    'helpful',
    'hostile',
    'indifferent',
    'unfriendly',
    'doomed',
    'dying',
    'unconscious',
    'wounded',
    'hidden',
    'observed',
    'undetected',
    'unnoticed',
    'clumsy',
    'drained',
    'enfeebled',
    'stupefied',
    'blinded',
    'concealed',
    'dazzled',
    'deafened',
    'invisible',
    'stunned',
    'slowed',
    'quickened',
    'petrified',
    'sickened',
    'restrained'
    }

CLEANER = r'<a style=.*?>|<a href=.*?>|<\/a>'

RUNES = {
    "Fanged": "You can transform into an animal with one action with the **interact** trait",
    "Fanged (Greater)": "You can transform into an animal and gain low-light vision and a +5 ft item bonus to Speed.",
    "Fanged (Major)": "You can transform into an animal and gain low-light vision, imprecise scent to a range of 30 ft, and a +10 ft item bonus to Speed.",
    "Authorized": "Non-authorized wielders take 1d8 **piercing damage** plus [[1d4]] **persistent bleed damage** per *striking* rune.",
    "Crushing": "Critical hits cause target to become **clumsy 1** and **enfeebled 1** until the end of your next turn.",
    "Crushing (Greater)": "Critical hits cause target to become **clumsy 2** and **enfeebled 2** until the end of your next turn.",
    "Kin-Warding": "When you use the weapon’s parry trait, you can point the clan dagger at an adjacent ally instead of defending yourself, creating a shield of runes around them. The runic barrier grants your ally the weapon’s circumstance bonus to AC, but you do not gain the bonus yourself.",
    "Returning": "When you make a thrown Strike with this weapon, it flies back to your hand after the Strike is complete. If your hands are full when the weapon returns, it falls to the ground in your space.",
    "Merciful": "Weapon gains the **nonlethal** trait and cannot cause **persistent damage**.  On critical hit, target becomes **fascinated** with the wielder for 1 minute.",
    "Bane": "Weapon deals [[1d6]] additional damage to chosen creatures.",
    "Earthbinding": "Once per hour, the rune casts *earthbind* (DC 20) when the attacker makes a critical hit on a flying creature with the etched weapon.",
    "Cunning": "Once per minute, as a free action following a damaging hit to a creature that has blood or other bodily fluids, attempt to *Recall Knowledge* about the target, gaining an item bonus to the skill check equal to the weapon's item bonus to attack rolls from its potency rune.  If the required attack was a critical hit, you also gain a +2 circumstance bonus to this check.",
    "Hooked": "Weapon gains the **trip** trait.  If the weapon normally has the **trip** trait, you can attempt to *Trip* a foe as a reaction when you critically hit it.",
    "Disrupting": "Deals an extra [[1d6]] **positive damage** to undead.  On a critical hit, the undead is also **enfeebled 1** until the end of your next turn.",
    "Disrupting (Greater)": "Deals an extra [[2d6]] **positive damage** to undead.  On a critical hit, the undead must make a DC 34 FORT save (**enfeebled 1** / **enfeebled 2** / **enfeebled 3** / destroyed).",
    "Pacifying": "As a mental reaction after damaging a creature, the creature must succeed at a DC 20 WILL save or be pacified (-2 penalty to attack rolls on any attacks that aren't nonlethal for 1 minute).",
    "Fearsome": "Target becomes **frightened 1** on successful hit.",
    "Fearsome (Greater)": "Target becomes **frightened 2** on successful hit.",
    "Demolishing": "When you damage a construct, you deal an extra [[1d6]] **persistent force damage**. On a critical hit, you deal an extra [[1d12]] **persistent force damage** instead.",
    "Hauling": "You gain a once per hour reaction after a successful hit to force the target to move 5 feet in the direction you choose (DC 20 REF negates).",
    "Hauling (Greater)": "You gain a once per hour reaction after a successful hit to force the target to move 10 feet in the direction you choose (DC 28 REF negates).",
    "Shifting": "With one action, you can shift the weapon into another melee weapon that requires the same number of hands to wield.",
    "Energizing": "After taking acid, cold, electricity, fire, or sonic damage, the weapon becomes imbued with the triggering energy type and does an additional 1d8 damage until the end of your next turn.",
    "Conducting": "Weapon gains the *resonant* trait, except this weapon deals an additional [[1d8]] instead of 1 damage per die when you *Conduct Energy*.  If the weapon already has the *resonant* trait, it deals [[1d8]] damage plus 1 damage per die.  On a critical hit, the weapon deals [[1d8]] **persistent damage** of the same type.",
    "Wounding": "Deal an extra [[1d6]] **persistent bleed damage** on hit.",
    "Deathdrinking": "Gain a +1 item bonus to saving throws against **negative damage** and **death** effects.  Deal an additional [[1d6]] **positive** or **negative damage**.  If you kill or destroy a creature, you gain a +1 item bonus to attack and damage rolls for 10 minutes.  If the creature was undead, you gain a number of temporary HP equal to twice your level for 10 minutes.",
    "Flurrying": "When you make a *Flurry of Blows* and your first Strike reduces a creature to 0 HP, you can make your second Strike with an echo of the weapon, increasing the reach to 30 ft.",
    "Giant-Killing": "Does an additional [[1d6]] **mental damage** on a successful Strike against a *giant*.  On a critical hit, the giant is also **enfeebled 1** until the end of your next turn.",
    "Giant-Killing (Greater)": "Does an additional [[2d6]] **mental damage** on a successful Strike against a *giant*.  On a critical hit, the giant must make a DC 34 FORT save (**enfeebled 1** / **enfeebled 2** and [[1d10]] additional **mental damage** / **enfeebled 3** for 1 minute and [[2d10]] additional **mental damage** / **enfeebled 4** for 1 minute and takes [[4d10]] additional **mental damage**).",
    "Corrosive": "Weapon deals an additional [[1d6]] **acid damage** on hit.  Critical hits deal [[3d6]] **acid damage** to the target's armor (or shield, if raised).",
    "Corrosive (Greater)": "Weapon deals an additional [[1d6]] **acid damage** on hit (not subject to acid resistance).  Critical hits deal [[6d6]] **acid damage** to the target's armor (or shield, if raised).",
    "Flaming": "Weapon deals an additional [[1d6]] **fire damage** on hit.  Critical hits deal [[1d10]] **persistent fire damage**",
    "Flaming (Greater)": "Weapon deals an additional [[1d6]] **fire damage** on hit.  Critical hits deal [[2d10]] **persistent fire damage**.  Damage ignores fire resistance.",
    "Frost": "Weapon deals an additional [[1d6]] **cold damage**.  Critical hits induce **slowed 1** until the end of your next turn unless target succeeds at a DC 24 FORT save.",
    "Frost (Greater)": "Weapon deals an additional [[1d6]] **cold damage**.  Critical hits induce **slowed 1** until the end of your next turn unless target succeeds at a DC 34 FORT save.  Damage ignores cold resistance.",
    "Shock": "Weapon deals an additional [[1d6]] **electricity damage**.  On a critical hit, electricity arcs out to deal an equal amount of **electricity damage** to up to two other creatures of your choice within 10 ft of the target.",
    "Shock (Greater)": "Weapon deals an additional [[1d6]] **electricity damage**.  On a critical hit, electricity arcs out to deal an equal amount of **electricity damage** to up to two other creatures of your choice within 10 ft of the target.  Damage ignores electricity resistance.",
    "Thundering": "Weapon deals an additional [[1d6]] **sonic damage**.  Critical hits induce **deafness** for 1 hour (DC 24 FORT save reduces to 1 minute).",
    "Thundering (Greater)": "Weapon deals an additional [[1d6]] **sonic damage**.  Critical hits induce permanent **deafness** (DC 34 FORT save reduces to 1 minute).  Damage ignores sonic resistance.",
    "Ashen": "Weapon deals [[1d4]] persistent fire damage and causes target to become **confused** for 1 round unless it succeeds at a DC 25 WILL save.",
    "Ashen (Greater)": "Weapon deals [[1d8]] persistent fire damage and causes target to become **confused** for 1 minute unless it succeeds at a DC 35 WILL save.",
    "Extending": "With two actions, you extend your weapon for an instant, giving you an impossible reach. You *Strike* with the weapon, and you have reach 60 feet for the Strike.",
    "Extending (Greater)": "With two actions, you extend your weapon for an instant, giving you an impossible reach. You *Strike* with the weapon, and you have reach 120 feet for the Strike.",
    "Swarming": "With two actions once per hour, you fling your weapon and it multiplies as it flies through the air, filling a 30-foot cone. All creatures within the area take damage equal to double the weapon's number of damage dice, with a DC 27 basic REF save.",
    "Impactful": "Weapon deals an additional [[1d6]] **force damage**.  On a critical hit, choose to push the target 5 ft away (DC 27 FORT save negates).",
    "Impactful (Greater)": "Weapon deals an additional [[1d6]] **force damage**.  On a critical hit, choose to push the target 10 ft away (DC 37 FORT save negates).",
    "Serrating": "Weapon deals an additional [[1d4]] damage.  With one action, speed up the serration.  The next hit does [[1d12]] damage instead.",
    "Holy": "Weapon deals an additional [[1d6]] **good damage** against evil targets.  Once per day, you can regain HP equal to double the evil creature's level after a critical hit.",
    "Unholy": "Weapon deals an additional [[1d6]] **evil damage** against evil targets.  Once per day, you can regain HP equal to double the good creature's level after a critical hit.",
    "Brilliant": "Weapon deals an additional [[1d4]] **fire damage**, [[1d4]] **good damage** to fiends, and [[1d4]] **positive damage** to undead.  On a critical hit, target must succeed at a DC 29 FORT save or be **blinded** for 1 round.",
    "Brilliant (Greater)": "Weapon deals an additional [[1d4]] **fire damage**, [[1d4]] **good damage** to fiends, and [[1d4]] **positive damage** to undead.  On a critical hit, target must succeed at a DC 41 FORT save or be **blinded** for 1 round.  Damage ignores resistance.",
    "Ghost Touch": "Weapon can harm creatures without physical form."
    }
